name: Release
on:
  push:
    branches:
      - main
      - dev
      - qa
      - uat
      - hotfix
  pull_request:
    branches:
      - main
      - dev
      - qa
      - uat

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures
        run: npm audit signatures

      - name: Build
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            npm run build:prod
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            npm run build:dev
          elif [ "${{ github.ref }}" = "refs/heads/qa" ]; then
            npm run build:qa
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            npm run build:uat
          else
            npm run build:dev
          fi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/qa' && 'qa' || github.ref == 'refs/heads/uat' && 'uat' || 'development' }}
        run: npx semantic-release